[lens]
name = "Nikkor AI AF Fisheye 16mm f/2.8D"
patent = "US Patent 5,434,713 (Nikon, 1995)"
focal_length = 16.0
max_fstop = 2.8
coating = "multi"

# Front group â€” negative meniscus elements

[[surface]]
radius = 69.258
thickness = 1.70
ior = 1.64
aperture = 105.22
abbe_v = 60.0

[[surface]]
radius = 15.165
thickness = 10.25
ior = 1.0
aperture = 58.6
abbe_v = 0.0

[[surface]]
radius = 130.305
thickness = 1.70
ior = 1.62041
aperture = 60.54
abbe_v = 60.1

[[surface]]
radius = 14.794
thickness = 4.00
ior = 1.0
aperture = 45.64
abbe_v = 0.0

# Cemented doublet

[[surface]]
radius = 32.412
thickness = 8.00
ior = 1.62588
aperture = 40.54
abbe_v = 35.7

[[surface]]
radius = -15.298
thickness = 9.00
ior = 1.79668
aperture = 40.54
abbe_v = 45.4

[[surface]]
radius = -38.75
thickness = 7.05
ior = 1.0
aperture = 28.96
abbe_v = 0.0

# Aperture stop

[[surface]]
type = "stop"
radius = 0.0
thickness = 3.93
ior = 1.0
aperture = 28.714
abbe_v = 0.0

# Cemented doublet

[[surface]]
radius = -81.004
thickness = 1.20
ior = 1.58144
aperture = 30.8
abbe_v = 40.8

[[surface]]
radius = 24.002
thickness = 5.00
ior = 1.51823
aperture = 33.22
abbe_v = 58.9

[[surface]]
radius = -20.608
thickness = 0.89
ior = 1.0
aperture = 33.22
abbe_v = 0.0

# Cemented doublet

[[surface]]
radius = 46.733
thickness = 5.50
ior = 1.5186
aperture = 39.26
abbe_v = 70.0

[[surface]]
radius = -19.219
thickness = 1.30
ior = 1.7847
aperture = 39.26
abbe_v = 26.1

[[surface]]
radius = -40.706
thickness = 0.85
ior = 1.0
aperture = 43.32
abbe_v = 0.0

# Rear filter plate

[[surface]]
radius = 0.0
thickness = 1.20
ior = 1.5168
aperture = 46.42
abbe_v = 64.1

[[surface]]
radius = 0.0
thickness = 0.0
ior = 1.0
aperture = 46.42
abbe_v = 0.0

[focus]
close_distance = 461.5288

[[focus.variable]]
surface = 10
thickness_close = 1.0964
