schema_version = "1.0.0"

id = "osl_camera"
version = "1.0.0"
name = "Physical Camera"
tagline = "Realistic lens simulation for Blender's OSL camera"
maintainer = "Peter Simonsson"
type = "add-on"

blender_version_min = "4.5.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
